### ISSUE TITLE
url in menus and breadcrumbs

### ISSUE THREAD

**Issue by denisb** [sakura-team/sakura#4]
* link or menu indicate sakura.imag.fr/Datas 
but leads to https://sakura-platform.liglab.fr/#Datas 
* sakura.imag.fr/#Datas => time out
* sakura.imag.fr/Datas => time out
* sakura-platform.liglab.fr/Datas =>404
* sakura-platform.liglab.fr/#Datas => OK !

**Comment by mikefromlig** [comment]
The links building has been revised.
