### ISSUE TITLE
sign in lost

### ISSUE THREAD

**Issue by denisb** [sakura-team/sakura#5]
When you ask to open most of the links (menus, breadcrumbs, ...) in another tab or window or when you refresh your tab (F5) you loose your credit and have to sign in again

**Comment by eduble** [comment]
This should be solved when commit 39b7662db49e3975eae2e9c09bc51c8f7d741113 is integrated into master and version is re-deployed. (to be verified at this time)

**Comment by eduble** [comment]
Fixed.
