### ISSUE TITLE
Create dataset from file without file

### ISSUE THREAD

**Issue by denisb** [sakura-team/sakura#7]
when you want to create a dataset from file
if you forget to give a file, the button "create table" is enabled (should be "create dataset" ?)
you can click on it
but it leads to infinite loop "creating table" (should be "creating dataset" ?)
and the created dataset seems corrupted

**Comment by eduble** [comment]
Do you mean giving a _name_ to the dataset?
I can confirm that a request to create a table was sent to the postgresql server yesterday, with empty table name, and that it made the daemon crash.

**Comment by mikefromlig** [comment]
Creating a dataset from a file is a two steps process: first we send the table creation, next we send the data to fill the table. When the sedond step fails the table can be created anyway.
--> Several feedbacks are now displayed to inform the user about possible issues when filling the table. Also, "create table" has been updated to "create dataset".
